spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/orbis_task_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: update
          show-sql: true
          format_sql: true


server:
    port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
